### ISSUE TITLE
Does it power blocks?

### ISSUE THREAD

**Issue by pandapaul** [ToroCraft/PowerProbe#2]
This block of text from the readme seems to indicate that the power probe actually delivers power, but it's just probing the power level right?

> Right clicking with the wand in hand will cause the power probe to power the block under the cursor. The power probe can only power blocks on faces that are adjacent to an air block. When the probe is powering a block, a small redstone block will be visible on the face of the block it is strongly powering.

**Comment by frodare** [comment]
It actually does provide power as advertised, similar to an actual power probe used for automotive work.  That feature turned out to be much harder than anticipated.

**Comment by pandapaul** [comment]
Oh ok.  Coo :D
